
###
GET http://localhost:5212

###
GET http://localhost:5212/v1/api/categories

###
GET http://localhost:5212/v1/api/categories/e01847b9-79f4-488f-94f7-e6ba7827da51

###
POST http://localhost:5212/v1/api/categories 
Content-Type: application/json

{
    "Name": "Home and Living",
    "Description": "Home and Living"
}

###
PUT http://localhost:5212/v1/api/categories/e01847b9-79f4-488f-94f7-e6ba7827da51
Content-Type: application/json

{
    "Name": "Coke",
    "Description": "non-israeli coke"
}
###
Delete http://localhost:5212/v1/api/categories/Coke
