
###
GET http://localhost:5212

###
GET http://localhost:5212/api/categories

###
POST http://localhost:5212/api/categories 
Content-Type: application/json

{
    "Name": "Beverages",
    "Description": "Non-Israili Beverages"
}

###
PUT http://localhost:5212/api/categories/08fcfa48-5800-4ed0-afd6-7d82faea1387
Content-Type: application/json

{
    "Name": "y",
    "Description": "1"
}
###
Delete http://localhost:5212/api/categories/xsdsfsdf